[mongodb]
mongodb

[redis]
redis

[mysql]
mysql

[rabbitmq]
rabbitmq

[catalogue]
catalogue

[user]
user

[cart]
cart

[shipping]
shipping

[payment]
payment

[dispatch]
dispatch

[frontend]
frontend 