[mongodb]
mongodb.cadb.online

[redis]
redis.cadb.online

[mysql]
mysql.cadb.online

[rabbitmq]
rabbitmq.cadb.online

[catalogue]
catalogue.cadb.online

[user]
user.cadb.online

[cart]
cart.cadb.online

[shipping]
shipping.cadb.online

[payment]
payment.cadb.online

[frontend]
cadb.online