- name: Install Python Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel

- name: app
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  pip: # will package work ?
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app

- name: restart service
  ansible.builtin.import_role:
    name: common
    tasks_from: restart
