- name: app
  ansible.builtin.import_role:
    name: common
    tasks_from: app

- name: restart service
  ansible.builtin.import_role:
    name: common
    tasks_from: restart

- name: mongodb client
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-client
  tags:
    - mongodb # tag lets you selectively run just the tasks with the same tag

- name: restart service
  ansible.builtin.import_role:
    name: common
    tasks_from: restart
  tags:
    - mongodb
