- name: install python3-pip
  package:
    name: python3-pip
    state: present
  become: true

- name: install boto3 and botocore
  pip:
    name:
      - boto3
      - botocore
    executable: pip3
  become: true
