- name: copy mongo repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client - mongodb-mongosh
  package:
    name: mongodb-mongosh
    state: present

- name: check catalogue database exists or not
  ansible.builtin.shell: >
    mongosh --host "{{ MONGODB_HOST }}" --quiet
    --eval 'db.getMongo().getDBNames().includes("catalogue")'
  register: catalogue_output
  changed_when: false

- name: print catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output.stdout }}"

- name: load products
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" < /app/db/master-data.js
  when: catalogue_output.stdout | trim != "true"
